parameters:
    env(DATABASE_URL): ''
    database_driver: pdo_sqlsrv
    database_host: 192.168.1.233
    database_port: 1433
    database_name: RIBEGROUPE_NEW
    database_user: sa
    database_password: 3Ribegroupe19!
    
    database_host2: 192.168.1.241
    database_port2: 1433
    database_name2: RIBEPRIM
    database_user2: sa
    database_password2: 2bsystem99!

doctrine:
    dbal:
        # url: '%env(resolve:DATABASE_URL)%'
        default_connection: default
        connections:
            default:
                driver: '%database_driver%'
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'

            customer:
                driver: '%database_driver%'
                host: '%database_host2%'
                port: '%database_port2%'
                dbname: '%database_name2%'
                user: '%database_user2%'
                password: '%database_password2%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
